Update gnsi-acctz.yang
openconfig/gnsi pull request #145
Opened 2024-01-24 15:29 UTC by marcushines

Remove duplicate container for counters

2024-01-24 15:32 UTC, greg-dennis commented on acctz/gnsi-acctz.yang
> -        container counters {
This leaves one too many closing braces in place.

2024-01-24 15:33 UTC, greg-dennis commented on acctz/gnsi-acctz.yang
>              container client-counters {
un-indent these children of the counters container?

2024-01-24 16:06 UTC, greg-dennis requested changes

2024-01-24 16:06 UTC, greg-dennis commented on acctz/gnsi-acctz.yang
> -            leaf last-cleared-on {
It's ok for this leaf to no longer exist anywhere?

2024-01-24 16:06 UTC, greg-dennis commented on acctz/gnsi-acctz.yang
> +            "Remove duplicate counter container.";
"counter" -> "counters"

2024-01-26 00:44 UTC, wenovus commented
We're looking at resolving these issues at https://github.com/openconfig/public/pull/1037

Propose to close this PR and move comments over there.

2024-02-01 17:46 UTC, closed without merging